#!/bin/bash

# --------------------------------------------------------------------
# Install and run tests in ~/tmp
#
# Usage:
#
# $ ./test_release 1.8.9.0
# --------------------------------------------------------------------

set -x

if [[ ! $1 ]] ; then 
  echo "Must set version as \$1 (e.g. 1.7)"
  exit 1
fi

vn=$1

# Get the major.minor Python version
py=$(python -V | cut -d " " -f 2 | cut -d "." -f 1,2)

mkdir -p ~/tmp

cp dist/cfunits-$vn.tar.gz ~/tmp
cd ~/tmp
rm -fr ~/tmp/test ~/tmp/bin ~/tmp/lib ~/tmp/cfunits-$vn

tar zxvf cfunits-$vn.tar.gz
cd cfunits-$vn

export PYTHONPATH=~/tmp/lib/python/cfunits-$vn-py$py.egg:$PYTHONPATH

python setup.py install --home=~/tmp

cd ~/tmp/lib/python/cfunits-$vn-py$py.egg/cfunits/test
python run_tests.py

set -x
