# A GitHub Action to run the cfunits test suite after events on master.
name: run test suite on ubuntu with mostly ubuntu packages
# Instead of running against the conda packages, we use here the packages
# from the used Linux distribution.

# Triggers the workflow on push or PR events for the master branch (only)
on:
  push:
    branches:
      - master
  pull_request:
    # default (from docs) is just on [opened, synchronize, reopened]
    types: [opened, reopened, ready_for_review, edited]
    branches:
      - master

jobs:
  run-test-suite-jobs:
    # Set-up the build matrix. We run on different distros and Python versions.
    strategy:
      matrix:
        # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
        # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    # check environment
    - name: check environment
      run: lsb_release -a
    - name: check python version
      run: python3 -V
    # update ubuntu repositories
    - name: apt-get update
      run: sudo apt-get update
    # install dependencies
    - name: install dependencies (ubuntu 18.04 packages)
      if: matrix.os == 'ubuntu-18.04'
      run: sudo apt-get install python3-setuptools python3-wheel libudunits2-0 python3-pycodestyle python3-coverage
    - name: install dependencies (ubuntu 20.04 packages)
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt-get install python3-setuptools python3-wheel libudunits2-0 python3-pycodestyle python3-coverage python3-numpy
    # Install cfunits
    # Important! Must install our development version of cfunits to test:
    # pip install -e .
    - name: install cfunits (ubuntu 18.04)
      if: matrix.os == 'ubuntu-18.04'
      run: pip3 install -e .
    - name: install cfunits (ubuntu 20.04)
      if: matrix.os == 'ubuntu-20.04'
      # https://github.com/pypa/pip/issues/7953
      run: pip3 install --user --no-use-pep517 -e .
    - name: python3 -c "import cfunits; print(cfunits.__file__)"
      run: |
        mkdir foo
        cd foo
        python3 -c "import cfunits; print(cfunits.__file__)"
    # Finally run the test suite and generate a coverage report!
    - name: Run test suite and generate a coverage report
      run: |
        cd cfunits/test
        ./run_tests_and_coverage --nohtml
